<%@ page contentType="text/html;charset=UTF-8" %>
<script src="${resource(dir: 'dataTables/js',file: 'jquery.dataTables.min.js')}"></script>
<script src="${resource(dir: 'datatables-plugins/integration/bootstrap/3',file: 'dataTables.bootstrap.min.js')}"></script>
<script src="${resource(dir: 'formValidation',file: 'formValidation.js')}"></script>
<script src="${resource(dir: 'formValidation/framework',file: 'bootstrap.min.js')}"></script>
<script src="${resource(dir: 'formValidation/language',file: 'es_ES.js')}"></script>
<script src="${resource(dir: 'bootstrap-dialog/js',file: 'bootstrap-dialog.min.js')}"></script>
<script src="${resource(dir: 'bootstrap-datepicker/js',file: 'bootstrap-datepicker.js')}"></script>
<script src="${resource(dir: 'bootstrap-datepicker/locales',file: 'bootstrap-datepicker.es.min.js')}"></script>